# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'data_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 731)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.model_change = QtWidgets.QComboBox(self.centralwidget)
        self.model_change.setGeometry(QtCore.QRect(0, 0, 191, 41))
        self.model_change.setObjectName("model_change")
        self.model_change.addItem("")
        self.model_change.addItem("")
        self.model_change.addItem("")
        self.model_change.addItem("")
        self.model_change.addItem("")
        self.model_change.addItem("")
        self.model_change.addItem("")
        self.picture_change = QtWidgets.QComboBox(self.centralwidget)
        self.picture_change.setGeometry(QtCore.QRect(500, 0, 191, 41))
        self.picture_change.setObjectName("picture_change")
        self.picture_change.addItem("")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(510, 630, 171, 41))
        self.label_2.setObjectName("label_2")
        self.view_text_change = QtWidgets.QComboBox(self.centralwidget)
        self.view_text_change.setGeometry(QtCore.QRect(230, 0, 211, 41))
        self.view_text_change.setObjectName("view_text_change")
        self.view_text_change.addItem("")
        self.view_text_change.addItem("")
        self.view_text_change.addItem("")
        self.view_text_change.addItem("")
        self.view_text_change.addItem("")
        self.view_place_widget = QtWidgets.QWidget(self.centralwidget)
        self.view_place_widget.setGeometry(QtCore.QRect(30, 70, 1131, 551))
        self.view_place_widget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.view_place_widget.setObjectName("view_place_widget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.model_change.setItemText(0, _translate("MainWindow", "可视化类型选择"))
        self.model_change.setItemText(1, _translate("MainWindow", "数据描述"))
        self.model_change.setItemText(2, _translate("MainWindow", "深度学习模型"))
        self.model_change.setItemText(3, _translate("MainWindow", "线性回归模型"))
        self.model_change.setItemText(4, _translate("MainWindow", "决策树回归模型"))
        self.model_change.setItemText(5, _translate("MainWindow", "随机森林回归模型"))
        self.model_change.setItemText(6, _translate("MainWindow", "梯度提升回归树模型"))
        self.picture_change.setItemText(0, _translate("MainWindow", "可视化图选择"))
        self.label_2.setText(_translate("MainWindow", "可视化结果展示区"))
        self.view_text_change.setItemText(0, _translate("MainWindow", "文本类型选择"))
        self.view_text_change.setItemText(1, _translate("MainWindow", "中国地震目录"))
        self.view_text_change.setItemText(2, _translate("MainWindow", "全球地震目录"))
        self.view_text_change.setItemText(3, _translate("MainWindow", "强震动参数数据集"))
        self.view_text_change.setItemText(4, _translate("MainWindow", "地震灾情数据列表"))
